name: rnaseq-sample
k8s:
  volume: nfs-pvc
  root_mount_path: "/data"
  volume_name: shared-volume
workflowDataset:
- var_name: genome_dir
  absolute_path: "/data/data/star-2.7.5c_GRCh38.d1.vd1_gencode.v36/"
- var_name: SRR6490021_1
  absolute_path: "/data/data/SRR6490021/SRR6490021_1.fastq"
- var_name: SRR6490021_2
  absolute_path: "/data/data/SRR6490021/SRR6490021_1.fastq"
jobs:
- name: star
  base_image: ghcr.io/martinluttap/star2:2.7.10b
  input:
  - var_name: star_in_genome_dir
    job:
    path: "${genome_dir}"
    type: file
  - var_name: star_in_SRR062641_1
    job:
    path: "${SRR6490021_1}"
    type: file
  - var_name: star_in_SRR062641_2
    job:
    path: "${SRR6490021_2}"
    type: file
  output:
  - var_name: star_out_SRR062641
    type: file
    path_relative: aligned.bam
  run_command:
    command:
    - "/bin/sh"
    - "-c"
    - "STAR --genomeDir ${genome_dir} --outFileNamePrefix aligned --runThreadN 96 --readFilesIn ${star_in_SRR062641_1} ${star_in_SRR062641_2}"
  metrics_identifier: star